version: '3'
services:
  
  datastore:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - '.mongodata:/data/db'

  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - "./:/app"
    depends_on:
      - "datastore"

  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask
